name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 16
          distribution: adopt
          cache: gradle

      - name: Build and Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew test

      - uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/reports/tests
