name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: Build and Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew test

      - name: Save Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/reports/tests

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v2
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
